import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";
import SessionProviderFun from "@/helpers/sessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProviderFun>
      <Navbar />
      {children}
      <Toaster />
    </SessionProviderFun>
  );
}
